//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomXdtTransforms.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EncryptedValue1")]
        public string ExpectedEncrypted1 {
            get {
                return ((string)(this["ExpectedEncrypted1"]));
            }
            set {
                this["ExpectedEncrypted1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SomeNotEncryptedValue1")]
        public string ExpectedNotEncrypted1 {
            get {
                return ((string)(this["ExpectedNotEncrypted1"]));
            }
            set {
                this["ExpectedNotEncrypted1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EncryptedValue2")]
        public string ExpectedEncrypted2 {
            get {
                return ((string)(this["ExpectedEncrypted2"]));
            }
            set {
                this["ExpectedEncrypted2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SomeNotEncryptedValue2")]
        public string ExpectedNotEncrypted2 {
            get {
                return ((string)(this["ExpectedNotEncrypted2"]));
            }
            set {
                this["ExpectedNotEncrypted2"] = value;
            }
        }
    }
}
